name: Staceywudesign
favicon: null
layout_spectrum: 0.36025348398834467
typography_spectrum: 0.26701176003552973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.07829390629194677
  lightness: 0.6934925373643637
  saturation: 0.4920023602899164
  rhythmicContrast: 0.7549110315740108
purpose: []
